"""Local DuckDB-backed preprocessing run viewer."""

from dr_code.viewer.analytics import ViewerAnalytics
from dr_code.viewer.database import DatabaseSchemaError, ViewerDatabase
from dr_code.viewer.domain import (
    Annotation,
    CandidateTestFailureClassificationInput,
    CandidateTestFailureClassificationInputs,
    IncompatibleRunsError,
    InvalidQueryError,
    InvalidTaskAnnotationError,
    MachineTaskAnnotationWriteOutcome,
    MachineTaskAnnotationWriteResult,
    ParseFailureClassificationInput,
    ParseFailureClassificationInputs,
    RunDescriptor,
    RunNotFoundError,
    RunValidationError,
    Tag,
    TaskAnnotation,
    TaskAnnotationOrigin,
    TaskAnnotationProvenance,
    TaskIdentity,
    TaskNotFoundError,
    Verdict,
    ViewerError,
)

__all__ = (
    "Annotation",
    "CandidateTestFailureClassificationInput",
    "CandidateTestFailureClassificationInputs",
    "DatabaseSchemaError",
    "IncompatibleRunsError",
    "InvalidQueryError",
    "InvalidTaskAnnotationError",
    "MachineTaskAnnotationWriteOutcome",
    "MachineTaskAnnotationWriteResult",
    "ParseFailureClassificationInput",
    "ParseFailureClassificationInputs",
    "RunDescriptor",
    "RunNotFoundError",
    "RunValidationError",
    "Tag",
    "TaskAnnotation",
    "TaskAnnotationOrigin",
    "TaskAnnotationProvenance",
    "TaskIdentity",
    "TaskNotFoundError",
    "Verdict",
    "ViewerAnalytics",
    "ViewerDatabase",
    "ViewerError",
)
