from __future__ import annotations

import dr_code.humaneval as humaneval


EXPECTED_HUMANEVAL_PUBLIC_API = {
    "CandidateNamespaceFailure",
    "CandidateNamespaceLoaded",
    "CandidateNamespaceOutcome",
    "CodeExtractionResult",
    "CompletedSubmissionResult",
    "ANY_CANDIDATE_HUMANEVAL_SCORING_PROFILE",
    "CandidateReduction",
    "DEFAULT_HUMANEVAL_SCORING_PROFILE",
    "EvaluationCaseStatus",
    "EvaluationCaseSummary",
    "EvaluationTaskSummary",
    "HUMANEVAL_CANDIDATE_ENTRY_POINT",
    "HUMANEVAL_CANDIDATE_JOB_SCHEMA_VERSION",
    "HUMANEVAL_ANY_CANDIDATE_SCORING_PROFILE_ID",
    "HUMANEVAL_ANY_CANDIDATE_SCORING_PROFILE_VERSION",
    "HUMANEVAL_SCORING_PROFILE_ID",
    "HUMANEVAL_SCORING_PROFILE_VERSION",
    "HUMANEVAL_METRICS_PROFILE",
    "HUMANEVAL_OVERRIDE_SET",
    "HUMANEVAL_OVERRIDE_SET_ID",
    "HUMANEVAL_OVERRIDE_SET_VERSION",
    "HarnessFailure",
    "HarnessFailureCause",
    "HumanEvalScoringProfile",
    "HumanEvalCandidateJobRequest",
    "HumanEvalCandidateJobResult",
    "HumanEvalEvaluatorSuite",
    "HumanEvalFunctionGroupResult",
    "HumanEvalMetricsProfile",
    "HumanEvalOverrideEntry",
    "HumanEvalOverrideSetCoordinate",
    "HumanEvalPlusTask",
    "HumanEvalSubmissionResult",
    "HumanEvalSubmissionRequest",
    "HumanEvalSuiteCompleted",
    "HumanEvalSuiteHarnessFailure",
    "HumanEvalSuiteResult",
    "HumanEvalTask",
    "HumanEvalTestCaseKind",
    "SampledHumanEvalTask",
    "SubmissionOutcome",
    "accept_first_surviving",
    "extract_humaneval_code",
    "evaluate_humaneval_candidate_job",
    "humaneval_runner",
    "load_humaneval_plus",
    "load_humaneval_rows",
    "parse_humaneval_dataset",
    "project_humaneval_submission",
    "project_humaneval_submissions_batch",
    "resolve_humaneval_scoring_profile",
    "sample_humaneval_tasks",
    "sample_humaneval_tasks_from_rows",
    "score_humaneval_submission",
    "score_humaneval_submissions_batch",
}


def test_humaneval_public_api_is_curated() -> None:
    assert set(humaneval.__all__) == EXPECTED_HUMANEVAL_PUBLIC_API
